# Generated by Django 4.2.9 on 2024-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='razao_social',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(default='nulo', max_length=200),
            preserve_default=False,
        ),
    ]
