# Generated by Django 4.2.9 on 2024-06-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_especialista_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='email',
            new_name='email_contato',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='email',
            new_name='email_contato',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='login',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='login',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.AddField(
            model_name='empresa',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='x_twitter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='especialista',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='especialista',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='especialista',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialista',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='especialista',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='especialista',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='x_twitter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email_contato',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='x_twitter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo_perfil', models.CharField(choices=[('Pessoa', 'Pessoa'), ('Especialista', 'Especialista'), ('Empresa', 'Empresa')], max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('login', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.perfil'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.perfil'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.perfil'),
        ),
    ]
