# Generated by Django 4.2.9 on 2024-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_empresa_cnpj_alter_especialista_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('Pessoa', 'Pessoa'), ('Especialista', 'Especialista'), ('Empresa', 'Empresa')], default='Pessoa', max_length=50),
        ),
    ]
