# Generated by Django 4.2.9 on 2024-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_perfil_tipo_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
