# Generated by Django 4.2.9 on 2024-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_perfil_options_perfil_descricao_pessoa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
