# Generated by Django 4.2.9 on 2024-07-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_perfil_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_resposta', models.DateTimeField()),
                ('situacao', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Respondido'), (2, 'Incompleto'), (3, 'Cancelado')], default=0)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.pessoa')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.questionario')),
                ('resposta', models.ManyToManyField(to='home.opcaoescolha')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.questionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opcaoescolha',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.questao'),
        ),
    ]
