# Generated by Django 4.2.9 on 2024-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_opcaoescolha_questionario_resposta_questao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
