# Generated by Django 4.2.9 on 2024-07-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_questionario_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CodigoAtivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=60)),
                ('x_twitter', models.CharField(blank=True, max_length=60)),
                ('instagram', models.CharField(blank=True, max_length=60)),
                ('codigo', models.IntegerField(blank=True, default=888888, max_length=8, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('perfil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
