# Generated by Django 4.2.9 on 2024-07-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_questao_options_alter_resposta_data_resposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoativacao',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='x_twitter',
        ),
    ]
