# Generated by Django 4.2.9 on 2024-07-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_codigoativacao_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoativacao',
            name='codigo',
            field=models.IntegerField(blank=True, default=888888, null=True),
        ),
    ]
