# Generated by Django 4.2.9 on 2024-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_codigoativacao_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoativacao',
            name='id',
        ),
        migrations.AlterField(
            model_name='codigoativacao',
            name='codigo',
            field=models.IntegerField(blank=True, default=888888, primary_key=True, serialize=False),
        ),
    ]
