# Generated by Django 4.2.9 on 2024-07-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_codigoativacao_id_alter_codigoativacao_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='questionarios',
            field=models.ManyToManyField(to='home.questionario'),
        ),
    ]
