# Generated by Django 4.2.9 on 2024-07-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_empresa_questionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='questionarios',
        ),
        migrations.CreateModel(
            name='QuestionarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_ativacao', models.DateTimeField(null=True)),
                ('data_inativacao', models.DateTimeField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
