# Generated by Django 4.2.9 on 2024-07-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_empresa_questionarios_questionarioempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='home.empresa'),
        ),
        migrations.AlterField(
            model_name='questionarioempresa',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='home.questionario'),
        ),
    ]
