# Generated by Django 4.2.9 on 2024-07-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_questionarioempresa_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioempresa',
            name='data_ativacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioempresa',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
