# Generated by Django 4.2.9 on 2024-07-22 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_empresa_login_mapeamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos_empresa', to='home.empresa')),
                ('questionarios', models.ManyToManyField(related_name='mapeamentos_questionarios', to='home.questionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapeamentoAtivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('usado', models.BooleanField()),
                ('unico', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='codigoativacao',
            name='empresa',
        ),
        migrations.AddField(
            model_name='codigoativacao',
            name='id',
            field=models.BigAutoField(auto_created=True, null=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigoativacao',
            name='codigo',
            field=models.CharField(blank=True, default='ABCD1234', max_length=8),
        ),
        migrations.DeleteModel(
            name='QuestionarioEmpresa',
        ),
        migrations.AddField(
            model_name='mapeamentoativacao',
            name='codigo_ativacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.codigoativacao'),
        ),
        migrations.AddField(
            model_name='mapeamentoativacao',
            name='mapeamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mapeamento'),
        ),
    ]
