# Generated by Django 4.2.9 on 2024-07-22 19:52

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("home", "CodigoAtivacao")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["ID"])

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_mapeamento_mapeamentoativacao_and_more'),
    ]

    operations = [
     
    ]
