# Generated by Django 4.2.9 on 2024-07-22 19:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20240722_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoativacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
