# Generated by Django 4.2.9 on 2024-07-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20240722_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='resposta',
            new_name='respostas',
        ),
    ]
