# Generated by Django 4.2.9 on 2024-07-24 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_rename_resposta_resposta_respostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='resposta',
            name='ativacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.codigoativacao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='mapeamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.mapeamento'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='participante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
