# Generated by Django 4.2.9 on 2024-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_resposta_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='ativacao',
            new_name='codigo_ativacao',
        ),
    ]
